	<meta charset="UTF-8">
	<style type="text/css">
		@import url('styles/main.css');
		@import url('styles/menu.css');
		@import url('styles/ui-lightness/jquery-ui.css');
		@import url('http://fonts.googleapis.com/css?family=Shadows+Into+Light');
		@import url('http://fonts.googleapis.com/css?family=Raleway:300,400');
	</style>
	<script type="text/javascript" src="js/jquery.js"></script>
	<script type="text/javascript" src="js/jquery-ui.js"></script>
	<script type="text/javascript" src="js/myscripts.js"></script>  
	<script type="text/javascript" src="js/cookie.js"></script>
	<script type="text/javascript" src="js/forms.js"></script>
	<link rel="icon" href="img/favicon.ico" type="image/x-icon" />